# Site settings
title: dickytrianza # site title
description: >- # site description
  He's writing in Bahasa about web technology and experience as a journal 
  for documentation things that he learned, meet him <a href="https://github.com/piharpi" target="_blank" rel="noopener">@github</a>.
lang: en-US # default lang
timezone: Asia/Jakarta # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/piharpi/jekyll-klise # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Dicky Aditrianza # author name
  bio: >- # tell to the world 
    Hai, saya Dicky, seorang mahasiswa Computer Science dengan minat di bidang Cyber Security dan Programming. Melalui web ini, saya tidak hanya berusaha membangun portofolio, tetapi juga menciptakan suatu ruang di mana saya bisa terus belajar dan mengekspresikan diri melalui blog. Saya akan menulis dalam bahasa Indonesia dan Inggris sebagai sarana untuk mengasah keterampilan belajar saya.  Kombinasi kedua bahasa ini juga menjadi refleksi dari dedikasi saya untuk terus berkembang dan beradaptasi dalam lingkungan teknologi yang dinamis.
    Topik-topik tulisan saya akan berkisar seputar dunia teknologi yang saya pelajari dan minati. Terakhir, saya ingin menekankan bahwa saya bukanlah seorang ahli, saya adalah seorang pembelajar yang tengah mengarungi perjalanan yang sama dalam memahami kompleksitas dunia IT.   

  username: corvuz # general username
  github: dickytrianza # github username
  email: daditrianza@email.com # email adress
  avatar: /assets/img/profile.jpeg # change with your own avatar

# URL settings
url: "https://klise.now.sh" #
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
